<a href="https://colab.research.google.com/github/ashish3127/hourse-and-humna-prediction-Deep-learning/blob/main/Predict_Horse_or_human.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here we are loading train CNN model to predict Given input(image) is Horse of Human

In [ ]:
# import Libraries
import numpy as np
import keras
from keras.preprocessing.image import ImageDataGenerator

Import model

In [ ]:
model_path1="/content/drive/MyDrive/cnn/horse-or-human.h5"

model1=keras.models.load_model(model_path1)

In [ ]:
h1="/content/drive/MyDrive/download (1).jpg"
h2="/content/drive/MyDrive/download (2).jpg"
h3="/content/drive/MyDrive/download.jpg"

In [ ]:
from keras.preprocessing import image
def pred_human_horse(model1,horse_or_human):
  test_image = image.load_img(horse_or_human, target_size =(150, 150))
  test_image = image.img_to_array(test_image)/255
  test_image =np.expand_dims(test_image, axis=0)

  result=model1.predict(test_image).round(3)

  pred =np.argmax(result)
  print(result, "--->>>", pred)

  if pred == 0:
    print("predict >> Horse")
  else:
    print("predict >>Human")  

Predict output

In [ ]:
for horse_or_human in [h1,h2,h3]:
  pred_human_horse(model1, horse_or_human)

[[1. 0.]] --->>> 0
predict >> Horse
[[0. 1.]] --->>> 1
predict >>Human
[[0.986 0.014]] --->>> 0
predict >> Horse
